name: Build TA-Lib wheels for Windows

on:
  workflow_dispatch:

env:
  TALIB_C_VER: 0.6.4
  TALIB_PY_VER: 0.6.3
  PIP_NO_VERIFY: 0
  PIP_VERBOSE: 1
  CIBW_BUILD_VERBOSITY: 2
  CIBW_BEFORE_BUILD: pip install -U setuptools wheel numpy Cython
  CIBW_TEST_REQUIRES: pytest pandas polars
  CIBW_TEST_COMMAND: >
    cd .. &&
    pytest --rootdir=C: -k "not RSI and not threading" {project}/tests
  CIBW_TEST_SKIP: "*win32 cp37* cp38* cp39*"
  CIBW_SKIP: "pp* cp36*"
  MSBUILDTREATHIGHERTOOLSVERSIONASCURRENT: 1

jobs:
  build_amd64:
    name: Build AMD64 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: build.cmd
        shell: cmd
      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_ENVIRONMENT_WINDOWS: >
            TA_LIBRARY_PATH="ta-lib-$TALIB_C_VER\\_build;$LIB"
            TA_INCLUDE_PATH="ta-lib-$TALIB_C_VER\\include;$INCLUDE"
            PIP_NO_BUILD_ISOLATION=false
      - name: ta-lib-everywhere
        run: |
          pip install wheel
          python << 'EOF'
          import glob, os, subprocess, shutil
          wheel_files = glob.glob('wheelhouse/*.whl')
          for wheel_file in wheel_files:
              print(f"Processing {wheel_file}...")
              subprocess.run(['wheel', 'unpack', wheel_file], check=True)
              base = os.path.splitext(os.path.basename(wheel_file))[0]
              unpack_dir = base  # 預設解包後目錄名稱為 <name>-<version>
              dist_info_dirs = [d for d in os.listdir(unpack_dir) if d.endswith('.dist-info')]
              if not dist_info_dirs:
                  continue
              dist_info_dir = os.path.join(unpack_dir, dist_info_dirs[0])
              metadata_path = os.path.join(dist_info_dir, 'METADATA')
              with open(metadata_path, 'r', encoding='utf-8') as f:
                  lines = f.readlines()
              with open(metadata_path, 'w', encoding='utf-8') as f:
                  for line in lines:
                      if line.startswith('Name:'):
                          f.write('Name: ta-lib-everywhere\n')
                      else:
                          f.write(line)
              subprocess.run(['wheel', 'pack', unpack_dir, '-d', 'wheelhouse'], check=True)
              shutil.rmtree(unpack_dir)
              os.remove(wheel_file)
          EOF
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-win-amd64

  build_x86:
    name: Build x86 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
      - run: build.cmd
        shell: cmd
      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_WINDOWS: x86
          CIBW_ENVIRONMENT_WINDOWS: >
            TA_LIBRARY_PATH="ta-lib-$TALIB_C_VER\\_build;$LIB"
            TA_INCLUDE_PATH="ta-lib-$TALIB_C_VER\\include;$INCLUDE"
            PIP_NO_BUILD_ISOLATION=false
      - name: ta-lib-everywhere
        run: |
          pip install wheel
          python << 'EOF'
          import glob, os, subprocess, shutil
          wheel_files = glob.glob('wheelhouse/*.whl')
          for wheel_file in wheel_files:
              print(f"Processing {wheel_file}...")
              subprocess.run(['wheel', 'unpack', wheel_file], check=True)
              base = os.path.splitext(os.path.basename(wheel_file))[0]
              unpack_dir = base
              dist_info_dirs = [d for d in os.listdir(unpack_dir) if d.endswith('.dist-info')]
              if not dist_info_dirs:
                  continue
              dist_info_dir = os.path.join(unpack_dir, dist_info_dirs[0])
              metadata_path = os.path.join(dist_info_dir, 'METADATA')
              with open(metadata_path, 'r', encoding='utf-8') as f:
                  lines = f.readlines()
              with open(metadata_path, 'w', encoding='utf-8') as f:
                  for line in lines:
                      if line.startswith('Name:'):
                          f.write('Name: ta-lib-everywhere\n')
                      else:
                          f.write(line)
              subprocess.run(['wheel', 'pack', unpack_dir, '-d', 'wheelhouse'], check=True)
              shutil.rmtree(unpack_dir)
              os.remove(wheel_file)
          EOF
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-win32
