name: Build TA-Lib Wheels (from GitHub)

on:
  workflow_dispatch:  # 手動觸發
  push:
    branches: [ "main" ]  # 當 push 到 main 分支時觸發

env:
  TA_LIB_PY_VERSION: "0.6.3"  # 最新版本

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.os }} / Py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.12']

    steps:
    - name: Checkout repository (optional but good practice)
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # --- 安裝 TA-Lib C 庫 (Ubuntu: 透過 apt-get 安裝) ---
    - name: Install TA-Lib C Library (Linux via apt-get)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y ta-lib libta-lib0-dev
        echo "TA-Lib C library installed via apt-get."
        echo "TA_INCLUDE_PATH=/usr/include" >> $GITHUB_ENV
        echo "TA_LIBRARY_PATH=/usr/lib" >> $GITHUB_ENV

    - name: Install TA-Lib C Library (macOS via Homebrew)
      if: runner.os == 'macOS'
      run: |
        echo "Updating Homebrew..."
        brew update --quiet
        echo "Installing TA-Lib C library..."
        brew install ta-lib
        echo "TA-Lib C library installed via Homebrew."
        echo "TA_LIBRARY_PATH=$(brew --prefix ta-lib)/lib" >> $GITHUB_ENV
        echo "TA_INCLUDE_PATH=$(brew --prefix ta-lib)/include" >> $GITHUB_ENV

    # --- 安裝 Python 構建依賴與 NumPy ---
    - name: Install Python build dependencies and NumPy
      run: python -m pip install --upgrade pip setuptools wheel build "numpy>=2.0"

    # --- 從 GitHub 直接 clone TA-Lib Python repository ---
    - name: Clone TA-Lib Python Repository
      run: |
        git clone https://github.com/ta-lib/ta-lib-python.git

    # --- 使用自訂的 setup.py 覆蓋原來的 setup.py ---
    - name: Override setup.py with custom version
      run: |
        cp custom_setup.py ta-lib-python/setup.py
        echo "Using custom setup.py:"
        head -n 10 ta-lib-python/setup.py

    # --- 從 clone 下來的程式碼構建 wheel ---
    - name: Build wheel from cloned repository
      run: |
        cd ta-lib-python
        echo "Building wheel for TA-Lib $TA_LIB_PY_VERSION..."
        python -m build --wheel . -o ../dist
        if [ $? -ne 0 ]; then
          echo "::error::Failed to build wheel from cloned repository."
          exit 1
        fi
        echo "Wheel build completed successfully."

    - name: List built wheel
      run: ls -l dist

    # --- 上傳生成的 wheel 作為 artifact ---
    - name: Upload Wheels
      uses: actions/upload-artifact@v4
      with:
        name: talib-wheel-${{ matrix.os }}-py${{ matrix.python-version }}-${{ env.TA_LIB_PY_VERSION }}
        path: dist/*.whl
        if-no-files-found: error
